# Project-wide Gradle settings.

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Fix for non-ASCII characters in path (Chinese folder name)
android.overridePathCheck=true

# Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
